
server:
  port: 8080


spring:
  datasource:
    url: jdbc:h2:mem:todo_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


jwt:
  secret: 72c4f5a6b7d8e9f0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z
  access-token:
    expiration: 3600000 # 1 hour
  refresh-token:
    expiration: 604800000 # 7 days



springdoc:
  swagger-ui:
    enabled: true


logging:
    level:
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE