
server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_test_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: 72c4f5a6b7d8e9f0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z
  access-token:
    expiration: 900000 # 15 минут
  refresh-token:
    expiration: 604800000 # 7 дней



springdoc:
  swagger-ui:
    enabled: true


logging:
    level:
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE